### ISSUE TITLE
Checklist of tasks to improve multiple morph functionality

### ISSUE THREAD

**Issue by Sparks29032** [diffpy/diffpy.pdfmorph#84]
To be fixed in branch `morph_sequence`
- [ ] Replace `--temperature` with `--sort-by=FIELD`
- [ ] Add `--reverse` tag
- [ ] Add `--metadata-filename`; a user can store FIELD data in that metadata file which PDFmorph can read from
- [ ] Add `--verbose` tag to condense output
- [ ] Make `multiple_morphs` and `single_morphs` functions more maintainable

To be fixed in in branch `change_libraries`
- [ ] Move to Pytest rather than Unittest
- [ ] Refactor test file names to specify which module is being tested
- [ ] Fix deprecation with `pkg_resources`

**Comment by sbillinge** [comment]
closed by #82
